### ISSUE TITLE
Error - Unterminated string in JSON at position 371 (line 1 column 372)

### ISSUE THREAD

**Issue by RobiGold1** [hamada2029/gphotos_sort#32]
Hello, today I received an error when sorting an album. Says: 
SyntaxError: Unterminated string in JSON at position 371 (line 1 column 372)
Call stack:   
    at JSON.parse (<anonymous>)
    at Album.parseAlbum (Album.js:98:42)
    at async Sorter.run (Sorter.js:163:23)

Album: 
   https://photos.app.goo.gl/8bHtsvV6XKRUFuDi8

Similar error was opened 2 days ago.
Could you please help ?

Thanks,

Robi

**Comment by wramey** [comment]
I'm seeing the same error message.
Running latest Chrome version 122.0.6261.129 (Official Build) (64-bit) on Windows.

**Comment by pizzabackup** [comment]
same error! If anyone can help with a fix that'd be awesome :)

**Comment by ant-rax** [comment]
Just stopped working withe the above mentioned error. This used to work....

**Comment by pizzabackup** [comment]
unfortunately I cannot approve the fix but it has already been provided here:

https://github.com/hamada2029/gphotos_sort/pull/30/files

i edited the line myself in my local copy, reloaded the extension (chrome://extensions, click the refresh button on the specific extension panel), and it works again!

Hope this can help you all.

**Comment by RobiGold1** [comment]
It works.

Thank you very much !!!

**Comment by ant-rax** [comment]
> unfortunately I cannot approve the fix but it has already been provided here:
> 
> https://github.com/hamada2029/gphotos_sort/pull/30/files
> 
> i edited the line myself in my local copy, reloaded the extension (chrome://extensions, click the refresh button on the specific extension panel), and it works again!
> 
> Hope this can help you all.

Thanks alot [pizzabackup](https://github.com/pizzabackup),
You saved my day!
