### ISSUE TITLE
TypeError: Cannot read properties of null (reading '0')

### ISSUE THREAD

**Issue by matthewgiv** [hamada2029/gphotos_sort#34]
Love this plugin, but it suddenly stopped working.

Getting error: **TypeError: Cannot read properties of null (reading '0') for albums large and small.**
Reinstalled, restarted, etc. and still happening.

Any ideas? Thanks in advance!

**Comment by bobpour** [comment]
I'm having the same issue. 
Iget below in console: 
TypeError: Cannot read properties of null (reading '0')
    at Album.parseAlbum (Album.js:105:41)
    at async Sorter.run (Sorter.js:163:23)

**Comment by sarathsanthan** [comment]
Facing the same issue. 

Found any solution ?

Thanks in advance!

**Comment by ant-rax** [comment]
Me too...

**Comment by jasonrmace** [comment]
The culprit seems to be in regex in `const script_p` on line 105 of Albums.js for me.

Either Google's API or something else has added an `id` to the script tags and the regex was seeing this and skipping. I changed the const from:
`const script_p = /<script nonce=[^{]+{key: *'ds:\d+'[^<]+<\/script>/g;`
to
`const script_p = /nonce=[^{]+{key: *'ds:\d+'[^<]+<\/script>/g`

and it worked for me. Someone who understands REGEX better than me can probably suggest a better solution.

Once I made the changes in the downloaded files, I then removed and re-installed this extension and it worked.

Hope this helps others!

**Comment by ant-rax** [comment]
Thanks a lot [jasonrmace](https://github.com/jasonrmace).  It works!

**Comment by matthewgiv** [comment]
You are the best, thank you!


INSTAGRAM <https://www.instagram.com/governorsinstitutesvt/> || FACEBOOK
<https://www.facebook.com/governorsinstitutesvt> || YOUTUBE
***@***.***> || LINKEDIN
<https://www.linkedin.com/school/governorsinstitutesvt> || LINKTREE
<https://linktr.ee/GovernorsInstitutesVT>

*Learn More About GIV <https://giv.org>*
*Donate to GIV* <https://givebutter.com/givt>

*Schedule A Meeting With Me <https://calendly.com/matthew-giv>*

**Comment by sarathsanthan** [comment]
Cant thank you enough for this @jasonrmace ! 
Highly appreciate it !

**Comment by bobpour** [comment]
same here... thanks @jasonrmace !

**Comment by SriAstitva** [comment]
PR #38 should fix this issue
